# Generated by Django 5.0.4 on 2024-06-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_listing_is_published_listing_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='test',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
